#!/bin/sh
#
# Jared Moskowitz
# decisionTreesWEKA
#
# This file runs and times SVM (not libsvm type) and BDT (10, 100, and 500 stumps)
# and outputs the results into "learnerTimes.txt"
#
# USAGE: ./SVMvsBDT [TRAINING FILE] [TEST FILE]

export CLASSPATH=/opt/shared/weka/weka-3-6-10/weka.jar:$CLASSPATH
export WEKADATA=/opt/shared/weka/weka-3-6-10/data

rm learnerTimes.txt

echo 'SVM Train: ' >> learnerTimes.txt
{ time java weka.classifiers.functions.SMO -t $1 -d svm.model -i -k -K "weka.classifiers.functions.supportVector.RBFKernel -C 250007 -G 0.01"; } 2>> learnerTimes.txt
echo 'SVM Test: ' >> learnerTimes.txt
{ time java weka.classifiers.functions.SMO -l svm.model -T $2; } 2>> learnerTimes.txt
echo 'BDT 10 iterations:' >> learnerTimes.txt
{ time java weka.classifiers.meta.AdaBoostM1 -W weka.classifiers.trees.DecisionStump -t $1 -T $2; } 2>> learnerTimes.txt
echo 'BDT 100 iterations:' >> learnerTimes.txt
{ time java weka.classifiers.meta.AdaBoostM1 -W weka.classifiers.trees.DecisionStump -I 100 -t $1 -T $2; } 2>> learnerTimes.txt
echo 'BDT 500 iterations:' >> learnerTimes.txt
{ time java weka.classifiers.meta.AdaBoostM1 -W weka.classifiers.trees.DecisionStump -I 500 -t $1 -T $2; } 2>> learnerTimes.txt
echo 'Done!'
