#!/bin/bash
#
# Jared Moskowitz
# logitBoostWEKA
#
# This file is intended to run logitBoosting method on given
# file. Feel free to play around with the parameters. When
# this was written the ada boosting was using decision stumps
#
# USAGE: ./decisionTreesWEKA [TRAINING FILE] [TEST FILE]

export CLASSPATH=/opt/shared/weka/weka-3-6-10/weka.jar:$CLASSPATH
export WEKADATA=/opt/shared/weka/weka-3-6-10/data

java weka.classifiers.meta.LogitBoost -W weka.classifiers.trees.DecisionStump -t $1 -T $2

