"""
trainandtest.py
Ben Nissan and Mukesh Ghimire

Trains and tests support vector machines (or SVMs) with libsvm to classify a set of provided data with different c and
gamma values. Provides information useful for determining the optimal values for these parameters: the number of support
vectors used, the number of false positives and negatives, and the overall efficiency (or accuracy).  Note: provided data
should be separated in advance into equally-sized training and testing groups.  Further information on this, and other
uses for libsvm, can be found in the libsvm documentation.

To run: python trainandtest.py trainFile testFile resultFile
"""

# Modules to interface with the command line and time the program
from os import system as command
from subprocess import Popen, PIPE
from sys import argv
from time import time

startTime = time()

# The training and testing sets, respectively
trainFile = argv[1]
testFile = argv[2]
resultFile = argv[3]

# Tables for our information: c and gamma values are
# selected in advance and used to calculate other values
Cs = [10 ** (float(n) / 4) for n in range(-12, 9)]
Gammas = [float(n) / 2 for n in range (2, 13)]
nSVs = []
FPFs = []
FNFs = []
efficiencies = []

# Trains the SVM and saves the number of support vectors used
def train(c, gamma, trainFile):
	trainCommand = ["./svm-train", "-c", str(c), "-g", str(gamma), trainFile]
	stdout = Popen(trainCommand, stdout = PIPE).stdout
	output = stdout.read()
	nSV = int(output.split("Total nSV = ")[1])
	nSVs.append(nSV)

# Renames model files to note chosen c and gamma values; files would otherwise
# overwrite each other each time a new one was created using the same data set
def rename(c, gamma, trainFile):
	newModel = trainFile + "c" + str(c) + "g" + str(gamma)
	renameCommand = "mv " + trainFile + ".model " + newModel + ".model"
	command(renameCommand)
	return newModel

# Tests the SVM on the test data set and removes now-unnecessary model files
def test(testFile, model):
	testCommand = "./svm-predict " + testFile + " " + model + ".model" + " " + model + "PR.txt"
	removeCommand = "rm " + model + ".model"
	command(testCommand)
	command(removeCommand)

# Compares the predicted classes generated by the SVM with the actual
# classes of the test data, calculates and saves false positives,
# negatives, and efficiency, and deletes now-unnecessary prediction files
def compare(testFile, model):
	data = []	# Real data
	results = []	# Predicted data

	signal = 0; background = 0
	falsePos = 0; falseNeg = 0

	# Imports real and predicted data into lists
	with open(testFile, 'r') as rawData:
		for line in rawData:
			data.append(int(line.split()[0]))

	with open(model + "PR.txt", 'r') as rawResults:
		for line in rawResults:
			results.append(int(line))

	# Checks for and increments signal, background, and false positives and negatives as necessary
	for i in range(len(data)):
		if data[i] == 1:
			signal += 1
		if data[i] == -1:
			background += 1
		if data[i] < results[i]:
			falsePos += 1
		elif data[i] > results[i]:
			falseNeg += 1

	
	# Calculates false positive and negative
	# fraction, as well as overall efficiency
	FPF = float(falsePos) / float(background)
	FNF = float(falseNeg) / float(signal)
	efficiency = 1 - FNF

	FPFs.append(FPF)
	FNFs.append(FNF)
	efficiencies.append(efficiency)
	removeCommand = "rm " + model + "PR.txt"
	command(removeCommand)

# Runs all of the above functions to perform a
# full run of the SVM for a given c and gamma.
def trainAndTest(c, gamma, trainFile, testFile):
	train(c, gamma, trainFile)
	model = rename(c, gamma, trainFile)
	test(testFile, model)
	compare(testFile, model)


# Performs a full SVM run for all of the given c and gamma
# values, saving all of the generated data in a new file
with open(resultFile, 'w') as results:

	i = 0

	for c in Cs:
		for gamma in Gammas:
			trainAndTest(c, gamma, trainFile, testFile)
			line = " ".join([str(c), str(gamma), str(nSVs[i]), str(FPFs[i]), str(FNFs[i]), str(efficiencies[i]), "\n"])
			results.write(line)
			i += 1

# Reports runtime
print "Total runtime: " + str(time() - startTime) + " seconds"