#!/bin/bash

python linearhardgen.py
python linearsoftgen.py
python circlehardgen.py
python circlesoftgen.py
python twocirclehardgen.py
python twocirclesoftgen.py
python twospherehardgen.py
python twospheresoftgen.py
python twospherehard1mgen.py
python twospheresoft1mgen.py