#!/bin/bash

python 8DHyperplaneHardGen.py
python 8DHyperplaneSoftGen.py
python 8DHypersphereHardGen.py
python 8DHypersphereSoftGen.py
python 8DTwoHypersphereHardGen.py
python 8DTwoHypersphereSoftGen.py
python CircleHardGen.py
python CircleSoftGen.py
python LinearHardGen.py
python LinearSoftGen.py
python PlaneHardGen.py
python PlaneSoftGen.py
python SphereHardGen.py
python SphereSoftGen.py
python TwoCircleHardGen.py
python TwoCircleSoftGen.py
python TwoSphereHardGen.py
python TwoSphereSoftGen.py