#!/bin/bash

python uniformgen.py
python linearhardgen.py
python linearsoftgen.py
python circlehardgen.py
python circlesoftgen.py
python twocirclehardgen.py
python twocirclesoftgen.py
python twospherehardgen.py
python twospheresoftgen.py
python twospherehard100kgen.py
python twospheresoft100kgen.py