#!/bin/bash
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM LinearHardTraining LinearHardTestingAll Results/LinearHardTestingAll0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM LinearHardTraining LinearHardTestingSignal Results/LinearHardTestingSignal0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM LinearHardTraining LinearHardTestingBackground Results/LinearHardTestingBackground0914

sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM LinearSoftTraining LinearSoftTestingAll Results/LinearSoftTestingAll0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM LinearSoftTraining LinearSoftTestingSignal Results/LinearSoftTestingSignal0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM LinearSoftTraining LinearSoftTestingBackground Results/LinearSoftTestingBackground0914


sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM CircleHardTraining CircleHardTestingAll Results/CircleHardTestingAll0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM CircleHardTraining CircleHardTestingSignal Results/CircleHardTestingSignal0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM CircleHardTraining CircleHardTestingBackground Results/CircleHardTestingBackground0914

sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM CircleSoftTraining CircleSoftTestingAll Results/CircleSoftTestingAll0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM CircleSoftTraining CircleSoftTestingSignal Results/CircleSoftTestingSignal0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM CircleSoftTraining CircleSoftTestingBackground Results/CircleSoftTestingBackground0914


sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM TwoCircleHardTraining TwoCircleHardTestingAll Results/TwoCircleHardTestingAll0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM TwoCircleHardTraining TwoCircleHardTestingSignal Results/TwoCircleHardTestingSignal0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM TwoCircleHardTraining TwoCircleHardTestingBackground Results/TwoCircleHardTestingBackground0914

sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM TwoCircleSoftTraining TwoCircleSoftTestingAll Results/TwoCircleSoftTestingAll0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM TwoCircleSoftTraining TwoCircleSoftTestingSignal Results/TwoCircleSoftTestingSignal0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM TwoCircleSoftTraining TwoCircleSoftTestingBackground Results/TwoCircleSoftTestingBackground0914


sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM PlaneHardTraining PlaneHardTestingAll Results/PlaneHardTestingAll0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM PlaneHardTraining PlaneHardTestingSignal Results/PlaneHardTestingSignal0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM PlaneHardTraining PlaneHardTestingBackground Results/PlaneHardTestingBackground0914

sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM PlaneSoftTraining PlaneSoftTestingAll Results/PlaneSoftTestingAll0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM PlaneSoftTraining PlaneSoftTestingSignal Results/PlaneSoftTestingSignal0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM PlaneSoftTraining PlaneSoftTestingBackground Results/PlaneSoftTestingBackground0914


sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM SphereHardTraining SphereHardTestingAll Results/SphereHardTestingAll0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM SphereHardTraining SphereHardTestingSignal Results/SphereHardTestingSignal0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM SphereHardTraining SphereHardTestingBackground Results/SphereHardTestingBackground0914

sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM SphereSoftTraining SphereSoftTestingAll Results/SphereSoftTestingAll0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM SphereSoftTraining SphereSoftTestingSignal Results/SphereSoftTestingSignal0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM SphereSoftTraining SphereSoftTestingBackground Results/SphereSoftTestingBackground0914


sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM TwoSphereHardTraining TwoSphereHardTestingAll Results/TwoSphereHardTestingAll0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM TwoSphereHardTraining TwoSphereHardTestingSignal Results/TwoSphereHardTestingSignal0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM TwoSphereHardTraining TwoSphereHardTestingBackground Results/TwoSphereHardTestingBackground0914

sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM TwoSphereSoftTraining TwoSphereSoftTestingAll Results/TwoSphereSoftTestingAll0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM TwoSphereSoftTraining TwoSphereSoftTestingSignal Results/TwoSphereSoftTestingSignal0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM TwoSphereSoftTraining TwoSphereSoftTestingBackground Results/TwoSphereSoftTestingBackground0914


sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DHyperplaneHardTraining 8DHyperplaneHardTestingAll Results/8DHyperplaneHardTestingAll0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DHyperplaneHardTraining 8DHyperplaneHardTestingSignal Results/8DHyperplaneHardTestingSignal0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DHyperplaneHardTraining 8DHyperplaneHardTestingBackground Results/8DHyperplaneHardTestingBackground0914

sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DHyperplaneSoftTraining 8DHyperplaneSoftTestingAll Results/8DHyperplaneSoftTestingAll0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DHyperplaneSoftTraining 8DHyperplaneSoftTestingSignal Results/8DHyperplaneSoftTestingSignal0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DHyperplaneSoftTraining 8DHyperplaneSoftTestingBackground Results/8DHyperplaneSoftTestingBackground0914


sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DHypersphereHardTraining 8DHypersphereHardTestingAll Results/8DHypersphereHardTestingAll0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DHypersphereHardTraining 8DHypersphereHardTestingSignal Results/8DHypersphereHardTestingSignal0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DHypersphereHardTraining 8DHypersphereHardTestingBackground Results/8DHypersphereHardTestingBackground0914

sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DHypersphereSoftTraining 8DHypersphereSoftTestingAll Results/8DHypersphereSoftTestingAll0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DHypersphereSoftTraining 8DHypersphereSoftTestingSignal Results/8DHypersphereSoftTestingSignal0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DHypersphereSoftTraining 8DHypersphereSoftTestingBackground Results/8DHypersphereSoftTestingBackground0914


sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DTwoHypersphereHardTraining 8DTwoHypersphereHardTestingAll Results/8DTwoHypersphereHardTestingAll0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DTwoHypersphereHardTraining 8DTwoHypersphereHardTestingSignal Results/8DTwoHypersphereHardTestingSignal0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DTwoHypersphereHardTraining 8DTwoHypersphereHardTestingBackground Results/8DTwoHypersphereHardTestingBackground0914

sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DTwoHypersphereSoftTraining 8DTwoHypersphereSoftTestingAll Results/8DTwoHypersphereSoftTestingAll0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DTwoHypersphereSoftTraining 8DTwoHypersphereSoftTestingSignal Results/8DTwoHypersphereSoftTestingSignal0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DTwoHypersphereSoftTraining 8DTwoHypersphereSoftTestingBackground Results/8DTwoHypersphereSoftTestingBackground0914


sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM MonteCarloTraining MonteCarloTestingAll Results/MonteCarloTestingAll0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM MonteCarloTraining MonteCarloTestingSignal Results/MonteCarloTestingSignal0914
sbatch -p largemem -c 4 --time=10080 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM MonteCarloTraining MonteCarloTestingBackground Results/MonteCarloTestingBackground0914
