#!/bin/bash
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM LinearHardTraining LinearHardTestingAll Results/LinearHardTestingAll0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM LinearHardTraining LinearHardTestingSignal Results/LinearHardTestingSignal0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM LinearHardTraining LinearHardTestingBackground Results/LinearHardTestingBackground0809

sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM LinearSoftTraining LinearSoftTestingAll Results/LinearSoftTestingAll0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM LinearSoftTraining LinearSoftTestingSignal Results/LinearSoftTestingSignal0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM LinearSoftTraining LinearSoftTestingBackground Results/LinearSoftTestingBackground0809


sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM CircleHardTraining CircleHardTestingAll Results/CircleHardTestingAll0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM CircleHardTraining CircleHardTestingSignal Results/CircleHardTestingSignal0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM CircleHardTraining CircleHardTestingBackground Results/CircleHardTestingBackground0809

sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM CircleSoftTraining CircleSoftTestingAll Results/CircleSoftTestingAll0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM CircleSoftTraining CircleSoftTestingSignal Results/CircleSoftTestingSignal0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM CircleSoftTraining CircleSoftTestingBackground Results/CircleSoftTestingBackground0809


sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM TwoCircleHardTraining TwoCircleHardTestingAll Results/TwoCircleHardTestingAll0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM TwoCircleHardTraining TwoCircleHardTestingSignal Results/TwoCircleHardTestingSignal0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM TwoCircleHardTraining TwoCircleHardTestingBackground Results/TwoCircleHardTestingBackground0809

sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM TwoCircleSoftTraining TwoCircleSoftTestingAll Results/TwoCircleSoftTestingAll0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM TwoCircleSoftTraining TwoCircleSoftTestingSignal Results/TwoCircleSoftTestingSignal0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM TwoCircleSoftTraining TwoCircleSoftTestingBackground Results/TwoCircleSoftTestingBackground0809


sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM PlaneHardTraining PlaneHardTestingAll Results/PlaneHardTestingAll0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM PlaneHardTraining PlaneHardTestingSignal Results/PlaneHardTestingSignal0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM PlaneHardTraining PlaneHardTestingBackground Results/PlaneHardTestingBackground0809

sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM PlaneSoftTraining PlaneSoftTestingAll Results/PlaneSoftTestingAll0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM PlaneSoftTraining PlaneSoftTestingSignal Results/PlaneSoftTestingSignal0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM PlaneSoftTraining PlaneSoftTestingBackground Results/PlaneSoftTestingBackground0809


sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM SphereHardTraining SphereHardTestingAll Results/SphereHardTestingAll0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM SphereHardTraining SphereHardTestingSignal Results/SphereHardTestingSignal0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM SphereHardTraining SphereHardTestingBackground Results/SphereHardTestingBackground0809

sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM SphereSoftTraining SphereSoftTestingAll Results/SphereSoftTestingAll0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM SphereSoftTraining SphereSoftTestingSignal Results/SphereSoftTestingSignal0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM SphereSoftTraining SphereSoftTestingBackground Results/SphereSoftTestingBackground0809


sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM TwoSphereHardTraining TwoSphereHardTestingAll Results/TwoSphereHardTestingAll0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM TwoSphereHardTraining TwoSphereHardTestingSignal Results/TwoSphereHardTestingSignal0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM TwoSphereHardTraining TwoSphereHardTestingBackground Results/TwoSphereHardTestingBackground0809

sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM TwoSphereSoftTraining TwoSphereSoftTestingAll Results/TwoSphereSoftTestingAll0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM TwoSphereSoftTraining TwoSphereSoftTestingSignal Results/TwoSphereSoftTestingSignal0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM TwoSphereSoftTraining TwoSphereSoftTestingBackground Results/TwoSphereSoftTestingBackground0809


sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DHyperplaneHardTraining 8DHyperplaneHardTestingAll Results/8DHyperplaneHardTestingAll0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DHyperplaneHardTraining 8DHyperplaneHardTestingSignal Results/8DHyperplaneHardTestingSignal0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DHyperplaneHardTraining 8DHyperplaneHardTestingBackground Results/8DHyperplaneHardTestingBackground0809

sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DHyperplaneSoftTraining 8DHyperplaneSoftTestingAll Results/8DHyperplaneSoftTestingAll0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DHyperplaneSoftTraining 8DHyperplaneSoftTestingSignal Results/8DHyperplaneSoftTestingSignal0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DHyperplaneSoftTraining 8DHyperplaneSoftTestingBackground Results/8DHyperplaneSoftTestingBackground0809


sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DHypersphereHardTraining 8DHypersphereHardTestingAll Results/8DHypersphereHardTestingAll0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DHypersphereHardTraining 8DHypersphereHardTestingSignal Results/8DHypersphereHardTestingSignal0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DHypersphereHardTraining 8DHypersphereHardTestingBackground Results/8DHypersphereHardTestingBackground0809

sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DHypersphereSoftTraining 8DHypersphereSoftTestingAll Results/8DHypersphereSoftTestingAll0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DHypersphereSoftTraining 8DHypersphereSoftTestingSignal Results/8DHypersphereSoftTestingSignal0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DHypersphereSoftTraining 8DHypersphereSoftTestingBackground Results/8DHypersphereSoftTestingBackground0809


sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DTwoHypersphereHardTraining 8DTwoHypersphereHardTestingAll Results/8DTwoHypersphereHardTestingAll0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DTwoHypersphereHardTraining 8DTwoHypersphereHardTestingSignal Results/8DTwoHypersphereHardTestingSignal0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DTwoHypersphereHardTraining 8DTwoHypersphereHardTestingBackground Results/8DTwoHypersphereHardTestingBackground0809

sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DTwoHypersphereSoftTraining 8DTwoHypersphereSoftTestingAll Results/8DTwoHypersphereSoftTestingAll0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DTwoHypersphereSoftTraining 8DTwoHypersphereSoftTestingSignal Results/8DTwoHypersphereSoftTestingSignal0809
sbatch -p largemem -c 4 --time=10000 --mem=50000 --output=SVM.%J.out --error=SVM.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunSVM 8DTwoHypersphereSoftTraining 8DTwoHypersphereSoftTestingBackground Results/8DTwoHypersphereSoftTestingBackground0809

