#!/bin/bash

python runSVM.py linearhardodds linearhardevens Results/linearhard0519
python runSVM.py linearsoftodds linearsoftevens Results/linearsoft0519
python runSVM.py circlehardodds circlehardevens Results/circlehard0519
python runSVM.py circlesoftodds circlesoftevens Results/circlesoft0519
python runSVM.py twocirclehardodds twocirclehardevens Results/twocirclehard0519
python runSVM.py twocirclesoftodds twocirclesoftevens Results/twocirclesoft0519