#!/bin/bash
sbatch -p largemem -c 4 --time=6480 --mem=20000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu run2DTree LinearHardTraining.arff LinearHardTestingAll.arff ResultsTree/LinearHardTestingAll0715
sbatch -p largemem -c 4 --time=6480 --mem=20000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu run2DTree LinearHardTraining.arff LinearHardTestingSignal.arff ResultsTree/LinearHardTestingSignal0715
sbatch -p largemem -c 4 --time=6480 --mem=20000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu run2DTree LinearHardTraining.arff LinearHardTestingBackground.arff ResultsTree/LinearHardTestingBackground0715

sbatch -p largemem -c 4 --time=6480 --mem=20000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu run2DTree LinearSoftTraining.arff LinearSoftTestingAll.arff ResultsTree/LinearSoftTestingAll0715
sbatch -p largemem -c 4 --time=6480 --mem=20000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu run2DTree LinearSoftTraining.arff LinearSoftTestingSignal.arff ResultsTree/LinearSoftTestingSignal0715
sbatch -p largemem -c 4 --time=6480 --mem=20000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu run2DTree LinearSoftTraining.arff LinearSoftTestingBackground.arff ResultsTree/LinearSoftTestingBackground0715


sbatch -p largemem -c 4 --time=6480 --mem=20000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu run2DTree CircleHardTraining.arff CircleHardTestingAll.arff ResultsTree/CircleHardTestingAll0715
sbatch -p largemem -c 4 --time=6480 --mem=20000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu run2DTree CircleHardTraining.arff CircleHardTestingSignal.arff ResultsTree/CircleHardTestingSignal0715
sbatch -p largemem -c 4 --time=6480 --mem=20000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu run2DTree CircleHardTraining.arff CircleHardTestingBackground.arff ResultsTree/CircleHardTestingBackground0715

sbatch -p largemem -c 4 --time=6480 --mem=20000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu run2DTree CircleSoftTraining.arff CircleSoftTestingAll.arff ResultsTree/CircleSoftTestingAll0715
sbatch -p largemem -c 4 --time=6480 --mem=20000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu run2DTree CircleSoftTraining.arff CircleSoftTestingSignal.arff ResultsTree/CircleSoftTestingSignal0715
sbatch -p largemem -c 4 --time=6480 --mem=20000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu run2DTree CircleSoftTraining.arff CircleSoftTestingBackground.arff ResultsTree/CircleSoftTestingBackground0715


sbatch -p largemem -c 4 --time=6480 --mem=20000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu run2DTree TwoCircleHardTraining.arff TwoCircleHardTestingAll.arff ResultsTree/TwoCircleHardTestingAll0715
sbatch -p largemem -c 4 --time=6480 --mem=20000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu run2DTree TwoCircleHardTraining.arff TwoCircleHardTestingSignal.arff ResultsTree/TwoCircleHardTestingSignal0715
sbatch -p largemem -c 4 --time=6480 --mem=20000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu run2DTree TwoCircleHardTraining.arff TwoCircleHardTestingBackground.arff ResultsTree/TwoCircleHardTestingBackground0715

sbatch -p largemem -c 4 --time=6480 --mem=20000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu run2DTree TwoCircleSoftTraining.arff TwoCircleSoftTestingAll.arff ResultsTree/TwoCircleSoftTestingAll0715
sbatch -p largemem -c 4 --time=6480 --mem=20000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu run2DTree TwoCircleSoftTraining.arff TwoCircleSoftTestingSignal.arff ResultsTree/TwoCircleSoftTestingSignal0715
sbatch -p largemem -c 4 --time=6480 --mem=20000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu run2DTree TwoCircleSoftTraining.arff TwoCircleSoftTestingBackground.arff ResultsTree/TwoCircleSoftTestingBackground0715


