#!/bin/bash
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree LinearHardTraining.arff LinearHardTestingAll.arff ResultsTree/LinearHardTestingAll0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree LinearHardTraining.arff LinearHardTestingSignal.arff ResultsTree/LinearHardTestingSignal0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree LinearHardTraining.arff LinearHardTestingBackground.arff ResultsTree/LinearHardTestingBackground0830

sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree LinearSoftTraining.arff LinearSoftTestingAll.arff ResultsTree/LinearSoftTestingAll0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree LinearSoftTraining.arff LinearSoftTestingSignal.arff ResultsTree/LinearSoftTestingSignal0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree LinearSoftTraining.arff LinearSoftTestingBackground.arff ResultsTree/LinearSoftTestingBackground0830


sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree CircleHardTraining.arff CircleHardTestingAll.arff ResultsTree/CircleHardTestingAll0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree CircleHardTraining.arff CircleHardTestingSignal.arff ResultsTree/CircleHardTestingSignal0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree CircleHardTraining.arff CircleHardTestingBackground.arff ResultsTree/CircleHardTestingBackground0830

sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree CircleSoftTraining.arff CircleSoftTestingAll.arff ResultsTree/CircleSoftTestingAll0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree CircleSoftTraining.arff CircleSoftTestingSignal.arff ResultsTree/CircleSoftTestingSignal0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree CircleSoftTraining.arff CircleSoftTestingBackground.arff ResultsTree/CircleSoftTestingBackground0830


sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree TwoCircleHardTraining.arff TwoCircleHardTestingAll.arff ResultsTree/TwoCircleHardTestingAll0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree TwoCircleHardTraining.arff TwoCircleHardTestingSignal.arff ResultsTree/TwoCircleHardTestingSignal0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree TwoCircleHardTraining.arff TwoCircleHardTestingBackground.arff ResultsTree/TwoCircleHardTestingBackground0830

sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree TwoCircleSoftTraining.arff TwoCircleSoftTestingAll.arff ResultsTree/TwoCircleSoftTestingAll0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree TwoCircleSoftTraining.arff TwoCircleSoftTestingSignal.arff ResultsTree/TwoCircleSoftTestingSignal0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree TwoCircleSoftTraining.arff TwoCircleSoftTestingBackground.arff ResultsTree/TwoCircleSoftTestingBackground0830


sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree PlaneHardTraining.arff PlaneHardTestingAll.arff ResultsTree/PlaneHardTestingAll0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree PlaneHardTraining.arff PlaneHardTestingSignal.arff ResultsTree/PlaneHardTestingSignal0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree PlaneHardTraining.arff PlaneHardTestingBackground.arff ResultsTree/PlaneHardTestingBackground0830

sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree PlaneSoftTraining.arff PlaneSoftTestingAll.arff ResultsTree/PlaneSoftTestingAll0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree PlaneSoftTraining.arff PlaneSoftTestingSignal.arff ResultsTree/PlaneSoftTestingSignal0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree PlaneSoftTraining.arff PlaneSoftTestingBackground.arff ResultsTree/PlaneSoftTestingBackground0830


sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree SphereHardTraining.arff SphereHardTestingAll.arff ResultsTree/SphereHardTestingAll0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree SphereHardTraining.arff SphereHardTestingSignal.arff ResultsTree/SphereHardTestingSignal0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree SphereHardTraining.arff SphereHardTestingBackground.arff ResultsTree/SphereHardTestingBackground0830

sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree SphereSoftTraining.arff SphereSoftTestingAll.arff ResultsTree/SphereSoftTestingAll0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree SphereSoftTraining.arff SphereSoftTestingSignal.arff ResultsTree/SphereSoftTestingSignal0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree SphereSoftTraining.arff SphereSoftTestingBackground.arff ResultsTree/SphereSoftTestingBackground0830


sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree TwoSphereHardTraining.arff TwoSphereHardTestingAll.arff ResultsTree/TwoSphereHardTestingAll0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree TwoSphereHardTraining.arff TwoSphereHardTestingSignal.arff ResultsTree/TwoSphereHardTestingSignal0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree TwoSphereHardTraining.arff TwoSphereHardTestingBackground.arff ResultsTree/TwoSphereHardTestingBackground0830

sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree TwoSphereSoftTraining.arff TwoSphereSoftTestingAll.arff ResultsTree/TwoSphereSoftTestingAll0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree TwoSphereSoftTraining.arff TwoSphereSoftTestingSignal.arff ResultsTree/TwoSphereSoftTestingSignal0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree TwoSphereSoftTraining.arff TwoSphereSoftTestingBackground.arff ResultsTree/TwoSphereSoftTestingBackground0830


sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree 8DHyperplaneHardTraining.arff 8DHyperplaneHardTestingAll.arff ResultsTree/8DHyperplaneHardTestingAll0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree 8DHyperplaneHardTraining.arff 8DHyperplaneHardTestingSignal.arff ResultsTree/8DHyperplaneHardTestingSignal0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree 8DHyperplaneHardTraining.arff 8DHyperplaneHardTestingBackground.arff ResultsTree/8DHyperplaneHardTestingBackground0830

sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree 8DHyperplaneSoftTraining.arff 8DHyperplaneSoftTestingAll.arff ResultsTree/8DHyperplaneSoftTestingAll0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree 8DHyperplaneSoftTraining.arff 8DHyperplaneSoftTestingSignal.arff ResultsTree/8DHyperplaneSoftTestingSignal0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree 8DHyperplaneSoftTraining.arff 8DHyperplaneSoftTestingBackground.arff ResultsTree/8DHyperplaneSoftTestingBackground0830


sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree 8DHypersphereHardTraining.arff 8DHypersphereHardTestingAll.arff ResultsTree/8DHypersphereHardTestingAll0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree 8DHypersphereHardTraining.arff 8DHypersphereHardTestingSignal.arff ResultsTree/8DHypersphereHardTestingSignal0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree 8DHypersphereHardTraining.arff 8DHypersphereHardTestingBackground.arff ResultsTree/8DHypersphereHardTestingBackground0830

sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree 8DHypersphereSoftTraining.arff 8DHypersphereSoftTestingAll.arff ResultsTree/8DHypersphereSoftTestingAll0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree 8DHypersphereSoftTraining.arff 8DHypersphereSoftTestingSignal.arff ResultsTree/8DHypersphereSoftTestingSignal0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree 8DHypersphereSoftTraining.arff 8DHypersphereSoftTestingBackground.arff ResultsTree/8DHypersphereSoftTestingBackground0830


sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree 8DTwoHypersphereHardTraining.arff 8DTwoHypersphereHardTestingAll.arff ResultsTree/8DTwoHypersphereHardTestingAll0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree 8DTwoHypersphereHardTraining.arff 8DTwoHypersphereHardTestingSignal.arff ResultsTree/8DTwoHypersphereHardTestingSignal0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree 8DTwoHypersphereHardTraining.arff 8DTwoHypersphereHardTestingBackground.arff ResultsTree/8DTwoHypersphereHardTestingBackground0830

sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree 8DTwoHypersphereSoftTraining.arff 8DTwoHypersphereSoftTestingAll.arff ResultsTree/8DTwoHypersphereSoftTestingAll0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree 8DTwoHypersphereSoftTraining.arff 8DTwoHypersphereSoftTestingSignal.arff ResultsTree/8DTwoHypersphereSoftTestingSignal0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree 8DTwoHypersphereSoftTraining.arff 8DTwoHypersphereSoftTestingBackground.arff ResultsTree/8DTwoHypersphereSoftTestingBackground0830


sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree MonteCarloTraining.arff MonteCarloTestingAll.arff ResultsTree/MonteCarloTestingAll0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree MonteCarloTraining.arff MonteCarloTestingSignal.arff ResultsTree/MonteCarloTestingSignal0830
sbatch -p largemem -c 4 --time=7200 --mem=50000 --output=BDT.%J.out --error=BDT.%J.err --mail-type=END,FAIL --mail-user=ben.nissan@tufts.edu RunBDTTree MonteCarloTraining.arff MonteCarloTestingBackground.arff ResultsTree/MonteCarloTestingBackground0830
