#!/bin/bash

python runBDTStump.py linearhardodds.arff linearhardevens.arff ResultsStump/linearhard0519
python runBDTStump.py linearsoftodds.arff linearsoftevens.arff ResultsStump/linearsoft0519
python runBDTStump.py circlehardodds.arff circlehardevens.arff ResultsStump/circlehard0519
python runBDTStump.py circlesoftodds.arff circlesoftevens.arff ResultsStump/circlesoft0519
python runBDTStump.py twocirclehardodds.arff twocirclehardevens.arff ResultsStump/twocirclehard0519
python runBDTStump.py twocirclesoftodds.arff twocirclesoftevens.arff ResultsStump/twocirclesoft0519
