#!/bin/bash

python runBDTTree.py linearhardodds.arff linearhardevens.arff ResultsTree/linearhard0519
python runBDTTree.py linearsoftodds.arff linearsoftevens.arff ResultsTree/linearsoft0519
python runBDTTree.py circlehardodds.arff circlehardevens.arff ResultsTree/circlehard0519
python runBDTTree.py circlesoftodds.arff circlesoftevens.arff ResultsTree/circlesoft0519
python runBDTTree.py twocirclehardodds.arff twocirclehardevens.arff ResultsTree/twocirclehard0519
python runBDTTree.py twocirclesoftodds.arff twocirclesoftevens.arff ResultsTree/twocirclesoft0519
