#!/bin/sh
#
# This will train and test a BDT model then plot the distances fro mthe hyperplane 
# NOTE: Must be in same directory as MainTrain.java and MaintTest.java
# USAGE: ./MasterBDTScripts [Training file].arff [Testing file].arff [# of stumps]
export CLASSPATH=/opt/shared/weka/weka-3-6-10/weka.jar:$CLASSPATH

module load java/1.7.0_51
javac MainTrain.java
#echo $3 >> times.txt
time java MainTrain $1 $3 >> times.txt
echo "Finished Training..."
sed -i '/return (double) maxI;/c\return sums;' ./AdaBoostClass.java
sed -i '0,/public static double classify(Object\[\] i)/s/public static double classify(Object\[\] i)/public static double\[\] classify(Object\[\] i)/' ./AdaBoostClass.java
s='Scores.txt'
scoreFile=$1$2$3$s
javac MainTest.java AdaBoostClass.java
java MainTest $2 $scoreFile
echo "Finished Testing..."
echo "Scores saved to " $scoreFile
#echo "Creating Plot..."
#python plotData.py $scoreFile $3
#t='TreeHist.png'
#p='Plot saved to '
#t3=$3$t
#echo $p$t3

rm *.class
